config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'homes#top'
  resources :snaps, only: [:new, :create, :index, :show, :destroy]
  resources :newss, only: [:new, :create, :index, :show, :destroy]
end
#アイテム作る
#deviseのやり直し

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/news.rb
class News < ApplicationRecord
  belongs_to :user
end

app/models/snap.rb
class Snap < ApplicationRecord
  belongs_to :user #snap:user=n:1
  attachment :snap_image #画像アップ用のメソッド（attachment）を追加してフィールド名に（snap_image）を指定
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :snaps, dependent: :destroy #user:snap=1:N
  has_many :newss, dependent: :destroy
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?
  #devise利用の機能（ユーザ登録、ログイン認証など）が使われる場合、その前にconfigure_permitted_parametersが実行

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name, :telephone, :address])
  end
  #ユーザ登録（sign_up）の際に、名前name、電話番号telephone、住所addressのデータ操作を許可
end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  def top
  end
end

app/controllers/newss_controller.rb
class NewssController < ApplicationController
  def new
    @news = News.new
  end

  def create
    @news = News.new(news_params)
    @news.user_id = current_user.id
    @news.save
    redirect_to newss_index_path
  end

  def index
    @newss = News.page(params[:page]).reverse_order
  end

  def show
    @news = News.find(params[:id])
  end

  def destroy
    @news = News.find(params[:id])
    @news.destroy
    redirect_to newss_index_path
  end

  private #一種の境界線、「ここから下はcontrollerの中でしか呼び出せません」
  #privateより後に定義されたメソッドは、アクションとして認識されなくなる

  def news_params #news_paramsではフォームで入力されたデータを受け取る
    params.require(:news).permit(:news_title, :news_body)
    #paramsはRailsで送られてきた値を受け取るためのメソッド
    #requireでデータのオブジェクト名(ここでは:news)を指定し、permitでキー（:title,:body）を指定
  end
end

app/controllers/snaps_controller.rb
class SnapsController < ApplicationController
  def new
    @snap = Snap.new
  end

  def create
    @snap = Snap.new(snap_params)
    @snap.user_id = current_user.id
    @snap.save
    redirect_to snaps_path
  end

  def index
    @snaps = Snap.page(params[:page]).reverse_order
  end

  def show
    @snap = Snap.find(params[:id])
  end

  def destroy
    @snap = Snap.find(params[:id])
    @snap.destroy
    redirect_to snaps_path
  end

  private

  def snap_params
    params.require(:snap).permit(:snap_image, :snap_comment)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/newss_helper.rb
module NewssHelper
end

app/helpers/snaps_helper.rb
module SnapsHelper
end

app/views/homes/top.html.erb
<h1>Top</h1>

<h2>ピックアップphoto×４</h2><!--item_showへリンク-->

<h2>メンズ、レディース、他アイテム</h2><!--item_indexへリンク-->

<h2>ショップニュース</h2><!--news_indexへ-->
<%= link_to "news_index", newss_index_path %>

<h2>Snap image</h2><!--snap_indexへリンク-->
<%= link_to "snap_index", snaps_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>EcSample</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
     <% if user_signed_in? %>
      <li>
        <%= link_to '投稿フォーム', new_snap_path %>
      </li>
      <li>
        <%= link_to "ログアウト", destroy_user_session_path, method: :delete %>
      </li>
    <% else %>
      <li>
        <%= link_to "新規登録", new_user_registration_path %>
      </li>
      <li>
        <%= link_to "ログイン", new_user_session_path %>
      </li>
    <% end %>
    <%= yield %>
  </body>
</html>

app/views/newss/index.html.erb
<h1>News一覧画面</h1>
<% @newss.each do |news| %>

<div>
  <p>Day:<%= news.created_at.strftime('%Y/%m/%d') %></p>
  <p>Title:<%= link_to newss_path(news.id) do %><%= news.news_title %><%end%></p>
  <p>Body: <%= news.news_body %></p>
</div>
<% end %>
<%= paginate @newss %>

app/views/newss/new.html.erb
<h1>ニュース投稿画面</h1>
<%= form_with model: @news, url:'/newss', local:true do |f| %>

<h4>Title</h4>
<%= f.text_field :news_title %>
<h4>Body</h4>
<%= f.text_area :news_body %>
<%= f.submit '投稿' %>
<% end %>

app/views/newss/show.html.erb
<h1>News詳細画面</h1>
<div>
  <p>Day:<%= @news.created_at.strftime('%Y/%m/%d') %></p>
  <p>Title:<%= @news.news_title %></p>
  <p>Body: <%= @news.news_body %></p>

  <% if @news.user == current_user %>
   <%= link_to "削除", newss_path(@news), method: :delete, "data-confirm" => "本当に削除しますか？" %> <!--投稿削除-->
  <% end %>
</div>

app/views/snaps/index.html.erb
<h1>Snap一覧画面</h1>
<% @snaps.each do |snap| %>
<!--コントローラから渡された@snaps変数内から1つずつ取り出して、snap変数へ格納-->
<div>
  <%= link_to snap_path(snap.id) do %>
    <%= attachment_image_tag snap, :snap_image %>
    <!--attachment_image_tagは、refile側が用意したヘルパーで、imgタグを作成。snap変数のsnap_image_idに保存された画像のimgタグを生成-->
  <% end %>
  <p>Name:<%= snap.user.name %></p>
  <p>Comment:<%= snap.snap_comment %></p>

</div>
<% end %>
<%= paginate @snaps %>

app/views/snaps/new.html.erb
<h1>Snap投稿画面</h1>
<%= form_with model: @snap, local:true do |f| %>
<!--orm_withを利用して、snaps_path（/snaps）に画像をアップロード-->

 <h4>Snap photo</h4>
 <%= f.attachment_field :snap_image %>
 <!--画像アップロード-->

 <h4>Comment</h4>
 <%= f.text_area :snap_comment %>

 <h4>Item</h4>
 <!--item nameでitem_showへリンク-->
 <%= f.submit '送信' %>

<% end %>

app/views/snaps/show.html.erb
<h1>Snap詳細画面</h1>
<div>
  <%= attachment_image_tag @snap, :snap_image %>
  <p>Name:<%= @snap.user.name %> <%= @snap.created_at.strftime('%Y/%m/%d') %></p>
  <p>Comment:<%= @snap.snap_comment %></p>
  <p>Item</p>
    <p></p>
    <p></p>
    <p><!--item nameでitem_showにリンク--></p>
    <p></p>
  <% if @snap.user == current_user %>
   <%= link_to "削除", snap_path(@snap), method: :delete, "data-confirm" => "本当に削除しますか？" %> <!--投稿削除-->
  <% end %>

</div>